
<?php
    $user = Auth::user()->group_id;
    $ext = ($user == 7? "layouts.sales":"layouts.app");
?>
@extends($ext)
@section('content')
  
   <div class="container">
  
  <ul class="nav nav-pills">
    <li class="active"><a data-toggle="pill" href="#home">Projects Deatils</a></li>
    <li><a data-toggle="pill" href="#menu1">Manufacturers</a></li>
    <li><a data-toggle="pill" href="#menu2">Enquiries</a></li>
    <li><a data-toggle="pill" href="#menu3">Orders </a></li>
    <li><a data-toggle="pill" href="#menu4">Business Generation </a></li>
    @if(Auth::user()->group_id == 2 || Auth::user()->group_id == 1)
    <li> 
       <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModals">Add Status</button>
   </li>
   @endif
  </ul><br><br>
  
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <table class="table" border="1">
        <thead>
          <tr>
                  <th>Project Name</th>
                  <th>Project Id</th>
                  <th>Address</th>
                  <th>Sub Ward Number</th>
                 <th>Project Status</th>

                 <th>Remarks</th>
                  <th>Contact No.</th>
                  <th>Whatsapp No.</th>
                  <th>Deleted On</th>
                  <th>Blocked Remarks</th>
                  
                </tr>
         </thead>  
         <tbody>
          @foreach($projects as $project)
             <tr>
              <td>{{ $project->procurementdetails->procurement_name ?? '' }}</td>
              <td><a href="{{ URL::to('/') }}/admindailyslots?projectId={{$project->project_id}}&&lename={{ $project->name }}" target="_blank">{{ $project->project_id }}</a></td>
              <td><a target="_blank" href="https://maps.google.co.in?q={{ $project->siteaddress->address ?? '' }}">{{ $project->siteaddress->address ?? '' }}</a></td>
              <td> {{ $project->subward->sub_ward_name ?? '' }}</td>
              <td>
                  {{$project->project_status}}

  </td>
  <td>
                  {{$project->remarks}}

  </td>
              <td>{{ $project->procurementdetails->procurement_contact_no ?? '' }}</td>
              <td>{{ $project->procurementdetails->whatsapp ?? '' }}</td>
              <td>
                  {{$project->deleted_at}}

  </td>
  <td>
                  {{$project->blockremark}}

  </td>
            </tr>
              @endforeach
         </tbody>       
         
       </table>
    </div>
    <div id="menu1" class="tab-pane fade">
       <table class="table" border="1">
        <thead>
          <tr>
                  <th>Manufacturer Name</th>
                  <th>Manufacturer Id</th>
                  <th>Address</th>
                 <th>Procurement Name</th>
                 <th>Remark</th>
                  <th>Contact No.</th>
                  <th>Whatsapp No.</th>
                  <th>Deleted On</th>
                  <th>Blocked Remarks</th>
                  <!-- <th>Updated By</th> -->
                </tr>
         </thead>  
         <tbody>
          @foreach($manufacturer as $project)
             <tr>
              <td>{{ $project->plant_name ?? '' }}</td>
              <td><a href="{{ URL::to('/') }}/viewmanu?id={{ $project->id }}">{{ $project->id }}</a></td>
              <td><a target="_blank" href="https://maps.google.co.in?q={{ $project->siteaddress->address ?? '' }}">{{ $project->address ?? '' }}</a></td>
              <td> {{ $project->proc->name ?? '' }}</td>
              <td> {{ $project->remarks ?? '' }}</td>
              <td>{{ $project->proc->contact ?? '' }}</td>
              <td>{{ $project->proc->whatsapp ?? '' }}</td>
              <td>{{ $project->deleted_at ?? '' }}</td>
              <td>{{ $project->lockremark ?? '' }}</td>
              <!-- <td>
             {{$project->updated_at}}<br>
             {{$project->user1->name ?? '' }}

           </td> -->
            </tr>
              @endforeach
         </tbody>       
         
       </table>
    </div>
    <div id="menu2" class="tab-pane fade">
       <table class="table" border="1">
        <thead>
          <tr>
                  <th>Enquiry Id</th>
                  <th>Project Id</th>
                  <th>Main Category </th>
                 <th>Status </th>
                  <th>Total Quantity .</th>
                  <th>Enquiry Generated By .</th>
                <!--   <th>Updated By</th> -->
                </tr>
         </thead>  
         <tbody>
          @foreach($enquiry as $project)
             <tr>
              <td><a href="{{ URL::to('/') }}/editenq?reqId={{ $project->id }}" >{{ $project->id ?? '' }}</a></td>
              <td><a href="{{ URL::to('/') }}/admindailyslots?projectId={{$project->project_id}}&&lename={{ $project->name }}" target="_blank">{{ $project->project_id }}</a>
           <a href="{{ URL::to('/') }}/viewmanu?id={{ $project->id }}">{{ $project->manu_id }}</a>

              </td>
              <td>{{ $project->main_category  ?? '' }}</td>
              <td> {{ $project->status  ?? '' }}</td>
              <td>{{ $project->total_quantity ?? '' }}</td>
              <?php $user= App\User::where('id',$project->generated_by)->pluck('name')->first(); ?>
              <td><b>{{ $user ?? '' }}</b></td>
              <!-- <td>
             {{$project->updated_at}}<br>
             {{$project->user->name ?? '' }}

           </td> -->
            </tr>
              @endforeach
         </tbody>       
         
       </table>
    </div>
    <div id="menu3" class="tab-pane fade">
      <table class="table" border="1">
        <thead>
          <tr>
                  <th>Order Id</th>
                  <th>Project Id</th>
                   <th>Enquiry Id</th>
                  <th>Brand </th>
                  <th>Status </th>
                  <th>quantity</th>
                </tr>
         </thead>  
         <tbody>
          @foreach($order as $project)
             <tr>
              <td>{{ $project->id ?? '' }}</td>
              <td><a href="{{ URL::to('/') }}/admindailyslots?projectId={{$project->project_id}}&&lename=" target="_blank">{{ $project->project_id }}</a>
           <a href="{{ URL::to('/') }}/viewmanu?id={{ $project->id }}">{{ $project->manu_id }}</a>
                
              </td>
              <td><a href="{{ URL::to('/') }}/editenq?reqId={{ $project->req_id }}" >{{ $project->req_id ?? '' }}</a></td>
              <td>{{ $project->brand  ?? '' }}</td>
              <td> {{ $project->status  ?? '' }}</td>
              <td>
             {{$project->quantity}}<br>
           </td>
            </tr>
              @endforeach
               @foreach($order1 as $project)
             <tr>
              <td>{{ $project->id ?? '' }}</td>
              <td><a href="{{ URL::to('/') }}/admindailyslots?projectId={{$project->project_id}}&&lename=" target="_blank"> {{ $project->project_id }} </a>
           <a href="{{ URL::to('/') }}/viewmanu?id={{ $project->id }}">{{ $project->manu_id }}</a>
                
              </td>
              <td><a href="{{ URL::to('/') }}/editenq?reqId={{ $project->req_id }}" >{{ $project->req_id ?? '' }}</a></td>
              <td>{{ $project->brand  ?? '' }}</td>
              <td> {{ $project->status  ?? '' }}</td>
              <td>
             {{$project->quantity}}<br>
           </td>
            </tr>
              @endforeach
         </tbody>       
         
       </table>
    </div>
    <div id="menu4" class="tab-pane fade">
        <table class="table" border="1">
        <thead> <?php $i=1; ?>
          <tr>
                  <th>Sl no </th>
                  <th>Invoice Number</th>
                  <th>Invoice Date</th>
                  <th>Order Inititor</th>
                  <th>Category</th>
                  <th>Total Amount</th>
                 
                </tr>
         </thead>  
         <tbody>
          @foreach($mh as $project)
             <tr>
             <td>{{$i++}}</td>
              <td>{{$project->invoiceno}}</td>
              <td>{{date('d-m-Y', strtotime($project->invoicedate ))  }}</td>
              <td><?php 
              $ini=App\Order::where('id',$project->order_id)->pluck('generated_by')->first(); 
              $user1=App\User::where('id',$ini)->pluck('name')->first(); ?> {{$user1}}
              </td>
              <td>{{$project->category }}</td>
              <td>{{ $project->mhInvoiceamount   ?? '' }}</td>

            </tr>
              @endforeach
               
              <tr>
              <td></td>
              <td></td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td>{{ $sumtotal}}</td>
            </tbody>       
         
       </table>
    </div>
  </div>
  
<div class="modal fade" id="myModals" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Select Status</h4>
        </div>
        <div class="modal-body">
          <form action="{{URL::to('/')}}/getcustomerremarks" method="post" id="ids{{$project->customer_id}}">
                 {{ csrf_field() }}
            
          <input type="hidden" name="cid" value="{{$_GET['customer_id']}}">
           <table class="table">
             
             <tr>
                <td>Select Status</td>
                <td>:</td>
                <td>                 
              <label><input required value="Closed Customers" id="dandw1" type="radio" name="Status"><span>&nbsp;</span>Closed Customers</label>
              <span>&nbsp;&nbsp;&nbsp;  </span>
           
              <label><input required value="Looking Credit" id="dandw2" type="radio" name="Status"><span>&nbsp;</span>Looking Credit</label>
              <span>&nbsp;&nbsp;&nbsp;  </span>
              <label><input required value="Blocked" id="dandw2" type="radio" name="Status"><span>&nbsp;</span>Block</label>
              <span>&nbsp;&nbsp;&nbsp;  </span>
           
              <label><input checked="checked" required value="Dealers" id="dandw3" type="radio" name="Status"><span>&nbsp;</span>Dealers</label>
                 <label><input checked="checked" required value="Others" id="dandw3" type="radio" name="Status"><span>&nbsp;</span>Others</label>
              <span>&nbsp;&nbsp;&nbsp;  </span>
                </td>
          </tr>
          <tr>
             <td>Remarks</td>
             <td>:</td>
             <td><textarea class="form-control" name="remarks">
               
             </textarea>
           </td>
         </tr>
           </table>
           <center><button class="btn btn-sm btn-warning" onclick="document.getElementById('ids{{$project->customer_id}}').submit()">Submit</button></center>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>


</div>
<script type="text/javascript">
  const cards = document.querySelectorAll('.card'),
      nexts = document.querySelectorAll('.card__next'),
      ixs = document.querySelectorAll('.card__index');
ixs.forEach((index, i) => {
  index.addEventListener('click', () => {
    for (let j = ixs.length - 1; j > i; j--) {
      cards[j].style.transform = 'translateX(100%)';
    }
    console.log(i);
  })
});
</script>
</body>
</html>

@endsection 






