@extends('layouts.app')

@section('content')
<div class="col-md-12">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default" style="border-color:green">
            <div class="panel-heading text-center" style="background-color:green">
                <b style="color:white">Tickets</b>
                <a  href="javascript:history.back()" class="btn btn-sm btn-danger btn-sm pull-right">Back</a> 
            </div>
             @if (session()->has('success'))
                    <center><h4 style="color:green;size:20px;">{{ session('message') }}</h4></center>
                    @endif
        <table  class="table table-responsive table-striped" border="1">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>project_id</th>
                        <th>brand</th>
                        <th>quantity</th>
                        <th>total</th>
                        <th>notes</th>
                        <th>generated by</th>
                        <th>subward</th>
                        <th>converted by</th>
                        
                        
                    </tr>
                </thead>

                <tbody>
                <?php $i = 1 ?>
          @foreach($data->order as $tickets)
          <tr>
           <td>{{$i++}}</td>
            <td>{{$tickets->project_id}}</td>
            <td>{{$tickets->brand}}</td>
            <td>{{$tickets->quantity}}</td>
            <td>{{$tickets->total}}</td>
            <td>{{$tickets->notes}}</td>
            <td>{{$tickets->generated_by}}</td>
            <td>{{$tickets->sub_ward_id}}</td>
            <td>{{$tickets->converted_by}}</td>

          </tr>
    
    @endforeach
                
</tbody>
</table>

</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
    function submit(arg){
        
        document.getElementById('submit'+arg).submit();
    }

</script>
@endsection