@extends('layouts.amheader')
@section('content')
<div class="col-md-12">
	<div class="panel panel-default" style="overflow-x: scroll;border-color:green">
		<div class="panel-heading text-center" style="background-color:green">
			<b style="color:white;font-size:1.4em">Orders</b>
			<a class="pull-right btn btn-sm btn-danger" href="{{ url()->previous() }}" id="btn1" style="color:white;"><b>Back</b></a>
		</div>
		<div class="panel-body">
		    
		    <table class="table table-responsive table-striped" border="1" id='table'>
				<thead>
				    <tr>
					    <th>Project ID</th>
					    <th>Order Id</th>
					    <th>Generated By</th>
						<th>Required</th>
						<th>Quantity</th>
						<th>Status</th>
						<th>Requirement Date</th>
						<th>Payment Status</th>
						<th>Dispatch Status</th>
						<th>Delivery Status</th>
						<th>Print Quotation</th>
						<th>&nbsp;&nbsp;&nbsp; Confirm Order &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					@foreach($view as $rec)
					<tr id="row-{{$rec->id}}">
						<td style="text-align:center"><a href="{{URL::to('/')}}/amshowProjectDetails?projectId={{$rec->project_id}}">{{$rec -> project_id}}</a></td>
						<td style="text-align:center">
						    {{ $rec->orderid }}
						</td>
						<td style="text-align:center" class="{{ Auth::user()->department_id == 1 && Auth::user()->group_id == 2?'hidden':''}}">{{ $rec->name }}</td>
						<td style="text-align:center">
							{{$rec -> main_category}}<br>
							{{$rec -> sub_category}}<br>
							{{$rec -> brand}}<br>
						</td>
						<td style="text-align:center">{{$rec->quantity}} {{$rec->measurement_unit}}</td>
						<td style="text-align:center">{{$rec->status}}</td>
						<td style="text-align:center" id="tddate{{$rec->id}}">{{ $newDateFormat2 = date('d/m/Y', strtotime($rec -> requirement_date)) }}</td>
						@if(Auth::user()->department_id == 5 && Auth::user()->group_id == 4)
                        <td style="text-align:center">
                            {{ $rec->payment_status }}
                        </td>
                        <td style="text-align:center">
                            @if($rec->dispatch_status)
	                            {{$rec->dispatch_status}}
                            @elseif(!$rec->dispatch_status)
	                            Not Yet Dispatched
                            @endif
                        </td>
						<td style="text-align:center">
							@if($rec -> delivery_status)
							    {{$rec -> delivery_status}}
						    @else
							    Not Delivered
						    @endif
						</td>
						<td>
						    <a href="{{URL::to('/')}}/{{$rec->orderid}}/printLPO" target="_blank" class="btn btn-sm btn-primary" >Print Quotation</a>
					    </td>
					    <td>
					    	@if($rec->status == "Enquiry Confirmed")
					    	<div class="btn-group">
						    	<button class="btn btn-sm btn-success pull-left" onclick="confirmamOrder('{{ $rec->orderid }}')">Confirm</button>
						    	<button class="btn btn-sm btn-danger pull-right" onclick="cancelamOrder('{{ $rec->orderid }}')">Cancel</button>
					    	</div>
					    	@else
					    	{{ $rec->status }}
					    	@endif
					    </td>
					    @endif
					</tr>
					@endforeach
				</tbody>	
			</table>
			<br>
			<center>{{$view->links()}}</center>	
		</div>
	</div>
</div>
<div class='b'></div>
<div class='bb'></div>
<div class='message'>
  <div class='check'>
    &#10004;
  </div>
  <p>
    Success
  </p>
  <p>
    @if(session('Success'))
    {{ session('Success') }}
    @endif
  </p>
  <button id='ok'>
    OK
  </button>
</div>
<script src="http://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">
	function filter()
	{
	    var date1 = document.getElementById('fromdate').value;
	    var date2 = document.getElementById('todate').value;
	    var filters = document.getElementById('filterorder');
	    var sel = filters.options[filters.selectedIndex].value;
	    alert(sel);
	    if(date2 < date1)
	    {
	        alert('To Date value should not be less than From Date !!!');
	        return false;
	    }
	    else
	    {
	        $.ajax({
	            type:'GET',
	            url: "{{URL::to('/')}}/filter",
	            data: {date1: date1, date2: date2, sel:sel},
	            async: false,
	            success: function(response)
	            {
	                document.getElementById('table').style.display = 'none';
	                var result = "<table class='table table-responsive table-striped' border='1' id='table'>";
	                result += "<thead><tr><th style='text-align:center'>Project ID</th><th style='text-align:center'></th></tr></thead>"
	                console.log(response);
	            }
	        });
	    }
	    return false;
	}
	function pay(arg)
	{
		var e = document.getElementById("selectPayment-"+arg);
		var strUser = e.options[e.selectedIndex].value;
		var ans = confirm('Are You Sure ?');
		if(ans){
			$.ajax({
				type: 'GET',
				url: "{{URL::to('/')}}/updatepay",
				data: {payment: strUser, id: arg},
				async: false,
				success: function(response){
					console.log(response);
				}
			});
		}
		return false;
	}
	function updateDispatch(arg)
	{
		var e = document.getElementById("selectdispatch-"+arg);
		var strUser = e.options[e.selectedIndex].value;
		var ans = confirm('Are You Sure ?');
		if(ans){
    		$.ajax({
    			type: 'GET',
    			url: "{{URL::to('/')}}/updatedispatch",
    			data: {dispatch: strUser, id: arg},
    			async: false,
    			success: function(response){
    				console.log(response);	
    			}
    		});
		}
		return false;	
	}
	
	
	function confirmamOrder(arg)
	{
	    var ans = confirm('Are You Sure To Confirm This Order ?');
	    if(ans)
	    {
    	    $.ajax({
    	       type:'GET',
    	       url: "{{URL::to('/')}}/confirmamOrder",
    	       data: {id : arg},
    	       async: false,
    	       success: function(response)
    	       {
    	           console.log(response);
    	           location.reload(true);
    	       }
    	    });
	    }    
	}
	
	function cancelamOrder(arg)
	{
	    var ans = confirm('Are You Sure To Cancel This Order ?');
	    if(ans)
	    {
    	    $.ajax({
    	       type:'GET',
    	       url: "{{URL::to('/')}}/cancelamOrder",
    	       data: {id : arg},
    	       async: false,
    	       success: function(response)
    	       {
    	           console.log(response);
    	           location.reload(true);
    	       }
    	    });
	    }
	 }
	 function placeOrder(arg)
	{
	    var ans = confirm('Are You Sure To Finally Place This Order ?');
	    if(ans)
	    {
    	    $.ajax({
    	       type:'GET',
    	       url: "{{URL::to('/')}}/placeOrder",
    	       data: {id : arg},
    	       async: false,
    	       success: function(response)
    	       {
    	           console.log(response);
    	           location.reload(true);
    	       }
    	    });
	    }
	 }


</script>
@endsection